#ifndef AINGTAFLATSCRIPTPARSER_H
#define AINGTAFLATSCRIPTPARSER_H


#if defined(AINGTAFlatScriptParser_LIBRARY)
#  define AINGTAFlatScriptParser_LIBRARY_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define AINGTAFlatScriptParser_LIBRARY_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AINGTAFSIICOMMANDS_H
