#ifndef GTAXMLRPCSERVERCLIENT_GLOBAL_H
#define GTAXMLRPCSERVERCLIENT_GLOBAL_H

#pragma warning(push, 0)
#include <QtCore/qglobal.h>
#pragma warning(pop)

#if defined(GTAXMLRPCSERVERCLIENT_LIBRARY)
#  define GTAXMLRPCSERVERCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GTAXMLRPCSERVERCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GTAXMLRPCSERVERCLIENT_GLOBAL_H
