#ifndef GTACOMMANDLIST_H
#define GTACOMMANDLIST_H


#include "GTAActionManual.h"
#include "GTAActionIF.h"
#include "GTAActionElse.h"
#include "GTAActionIRT.h"
#include "GTAOneClick.h"
#include "GTACheckValue.h"
#include "GTAActionSet.h"
#include "GTAActionSetList.h"
#include "GTAActionPrint.h"
#include "GTAActionWait.h"
#include "GTAActionWhile.h"
#include "GTACheckFwcWarning.h"
#include "GTACheckBiteMessage.h"
#include "GTAActionRelease.h"
#include "GTACheckAudioAlarm.h"
#include "GTAActionOneClickPPC.h"
#include "GTAOneClickLaunchApplication.h"
#include "GTAActionRoboArm.h"
#include "GTAActionPrintTable.h"
#include "GTAActionParentTitle.h"
#include "GTAActionMaths.h"
#include "GTAActionMath.h"
#include "GTAActionOneClickSetList.h"
#include "GTAActionDoWhile.h"
#include "GTAActionGenericFunction.h"
#include "GTAActionOneClickParentTitle.h"
#include "GTAActionExpandedCall.h"
#include "GTAActionPrintTime.h"
#include "GTAActionFunctionReturn.h"
#include "GTAActionCallProcedures.h"
#include "GTAInvalidCommand.h"
#include "GTAActionFailure.h"
#include "GTAEquationBase.h"
#include "GTAEquationConst.h"
#include "GTAGenericToolCommand.h"
#include "GTAActionSubscribe.h"
#include "GTAActionUnSubscribe.h"
#include "GTAActionDoWhileEnd.h"
#include "GTAActionIfEnd.h"
#include "GTAActionWhileEnd.h"
#include "GTAActionForEach.h"
#include "GTAActionForEachEnd.h"


#endif // GTACOMMANDLIST_H
