name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    env:
      QT_VERSION: '5.15.2'  # Centralized version management
      QT_ARCH: 'win64_msvc2019_64'
      BUILD_CONFIG: 'Release'
      BUILD_PLATFORM: 'x64'

    steps:
      # Step 1: Checkout with full history
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Step 2: Install Qt with caching
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          arch: ${{ env.QT_ARCH }}
          install-deps: true
          modules: 'qtbase,qttools,qtdeclarative'
          cached: true  # Enable caching for faster subsequent runs

      # Step 3: Set up MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.0'

      # Step 4: Configure Qt environment
      - name: Configure Qt Paths
        shell: pwsh
        run: |
          $qtPath = "C:\Qt\${{ env.QT_VERSION }}\${{ env.QT_ARCH }}"
          echo "QT_DIR=$qtPath" >> $env:GITHUB_ENV
          echo "PATH=$qtPath\bin;$env:PATH" >> $env:GITHUB_ENV
          echo "QMAKESPEC=win32-msvc" >> $env:GITHUB_ENV

      # Step 5: Verify Qt installation
      - name: Verify Qt Installation
        shell: pwsh
        run: |
          if (-not (Test-Path "$env:QT_DIR\bin\qmake.exe")) {
            Write-Error "Qt installation verification failed - qmake not found"
            exit 1
          }
          Write-Output "Qt verified at $env:QT_DIR"

      # Step 6: Install SonarScanner
      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.13.0
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Step 7: Initialize SonarScanner with timeout
      - name: Initialize SonarScanner
        timeout-minutes: 5
        run: |
          dotnet sonarscanner begin `
            /k:"Durgesh-byte_GTA-Editor-New" `
            /o:"${{ secrets.SONAR_ORG }}" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.verbose=true `
            /d:sonar.cfamily.build-wrapper-output=bw-output `
            /d:sonar.cfamily.cache.enabled=true

      # Step 8: Build with improved logging
      - name: Build Solution
        timeout-minutes: 30
        shell: pwsh
        run: |
          msbuild GTAAPPLICATION.sln `
            -t:rebuild `
            -p:Qt5_DIR="$env:QT_DIR" `
            -p:Configuration=${{ env.BUILD_CONFIG }} `
            -p:Platform=${{ env.BUILD_PLATFORM }} `
            -verbosity:diagnostic `
            -nr:false `
            -bl:msbuild.binlog

      # Step 9: Finalize SonarScanner
      - name: Finalize SonarScanner
        if: always()
        timeout-minutes: 5
        run: |
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # Step 10: Upload diagnostics
      - name: Upload Diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-${{ github.run_id }}
          path: |
            msbuild.binlog
            *.log
            **/*.log
