name: Build GTA-Editor-New with Qt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python (required for aqtinstall)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'
        check-latest: false
        update-environment: true
        allow-prereleases: false
        freethreaded: false

    # Step 3: Install Qt 5.15.2
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.2
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        dir: C:\Qt  # Install Qt to C:\Qt, so Qt will be at C:\Qt\5.15.2\msvc2019_64
        install-deps: true
        cache: false
        cache-key-prefix: install-qt-action
        setup-python: true
        add-tools-to-path: true
        set-env: true
        no-qt-binaries: false
        tools-only: false
        aqtversion: ==3.1.*
        py7zrversion: ==0.20.*
        source: false
        documentation: false
        examples: false

    # Step 4: Set up MSVC environment
    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: 14.29  # Corresponds to MSVC 2019 (v143 toolset)

    # Step 5: Fix GTAXmlRpcServerClient.vcxproj to remove missing source file
    - name: Remove missing GTAXmlRpcServerClient.cpp from project file
      run: |
        $projectFile = "src\GTAXmlRpcServerClient\GTAXmlRpcServerClient.vcxproj"
        $content = Get-Content $projectFile -Raw
        $updatedContent = $content -replace '<ClCompile Include="src\\GTAXmlRpcServerClient.cpp" />', ''
        Set-Content $projectFile $updatedContent -NoNewline
      shell: pwsh

    # Step 6: Set Qt environment variables for MSBuild
    - name: Set Qt environment variables
      run: |
        echo "QTDIR=C:\Qt\5.15.2\msvc2019_64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Qt5_Dir=C:\Qt\5.15.2\msvc2019_64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    # Step 7: Build the solution
    - name: Build the solution
      run: |
        msbuild GTAApplication.sln -p:Configuration=Release -p:Platform=x64 -maxcpucount
      env:
        QTDIR: C:\Qt\5.15.2\msvc2019_64
        Qt5_Dir: C:\Qt\5.15.2\msvc2019_64

    # Step 8: Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gta-editor-build-artifacts
        path: build/Release/
