name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Step 2: Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'
          install-deps: true
          modules: 'qtbase,qttools,qtdeclarative'

      # Step 3: Set up MSBuild
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.0'

      # Step 4: Configure Qt environment
      - name: Set Qt Environment
        shell: pwsh
        run: |
          $qtPath = "C:\Qt\5.15.2\msvc2019_64"
          echo "QT_DIR=$qtPath" >> $env:GITHUB_ENV
          echo "PATH=$qtPath\bin;$env:PATH" >> $env:GITHUB_ENV
          echo "QMAKESPEC=win32-msvc" >> $env:GITHUB_ENV

      # Step 5: Verify Qt installation
      - name: Verify Qt Installation
        shell: pwsh
        run: |
          Get-ChildItem "$env:QT_DIR\bin\qmake.exe"
          Get-ChildItem "$env:QT_DIR\include\QtCore"

      # Step 6: Install SonarScanner
      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.13.0
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Step 7: Initialize SonarScanner
      - name: Initialize SonarScanner
        run: |
          dotnet sonarscanner begin /k:"Durgesh-byte_GTA-Editor-New" `
            /o:"${{ secrets.SONAR_ORG }}" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.verbose=true `
            /d:sonar.cfamily.build-wrapper-output=bw-output

      # Step 8: Build solution
      - name: Build Solution
        shell: pwsh
        run: |
          msbuild GTAAPPLICATION.sln `
            -t:rebuild `
            -p:Qt5_DIR="$env:QT_DIR" `
            -p:Configuration=Release `
            -p:Platform="x64" `
            -verbosity:diagnostic

      # Step 9: Finalize SonarScanner (always run)
      - name: Finalize SonarScanner
        if: always()
        run: |
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # Step 10: Upload logs if build fails (using v4 of upload-artifact)
      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            *.log
            **/*.log
