name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.0'

      - name: Install Qt
        run: choco install qt5-default -y

      - name: Set Qt Environment Variables
        run: |
          echo "C:\Qt\5.15.2\msvc2019\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Qt\5.15.2\msvc2019\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify Qt Installation
        run: qmake --version

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"Durgesh-byte_GTA-Editor-New" /o:"${{ secrets.SONAR_ORG }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.verbose=true

      - name: Build with MSBuild
        run: |
          msbuild GTAAPPLICATION.sln -t:rebuild -verbosity:diagnostic

      - name: End SonarScanner
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
