name: Build GTA-Editor-New with Qt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python (required for aqtinstall)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'
        check-latest: false
        update-environment: true
        allow-prereleases: false
        freethreaded: false

    # Step 3: Install Qt 5.15.2
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.2
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        dir: C:\Qt  # Install Qt to C:\Qt, so Qt will be at C:\Qt\5.15.2\msvc2019_64
        install-deps: true
        cache: false
        cache-key-prefix: install-qt-action
        setup-python: true
        add-tools-to-path: true
        set-env: true
        no-qt-binaries: false
        tools-only: false
        aqtversion: ==3.1.*
        py7zrversion: ==0.20.*
        source: false
        documentation: false
        examples: false

    # Step 4: Set up MSVC environment
    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: 14.29  # Corresponds to MSVC 2019 (v143 toolset)

    # Step 5: Build the solution with Qt paths
    - name: Build the solution
      run: |
        msbuild GTAApplication.sln -p:Configuration=Release -p:Platform=x64 -maxcpucount `
          -p:AdditionalIncludeDirectories="C:\Qt\5.15.2\msvc2019_64\include;C:\Qt\5.15.2\msvc2019_64\include\QtCore;C:\Qt\5.15.2\msvc2019_64\include\QtXml;C:\Qt\5.15.2\msvc2019_64\include\QtNetwork;C:\Qt\5.15.2\msvc2019_64\include\QtGui;C:\Qt\5.15.2\msvc2019_64\include\QtWidgets;C:\Qt\5.15.2\msvc2019_64\include\QtSql" `
          -p:AdditionalLibraryDirectories="C:\Qt\5.15.2\msvc2019_64\lib"
      shell: pwsh

    # Step 6: Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gta-editor-build-artifacts
        path: build/Release/
