name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'  # Replace with your Qt version (e.g., 5.15.2)
          install-deps: true  # Installs Qt dependencies (like MSVC)

      # Step 3: Set up MSBuild
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      # Step 4: Install SonarScanner
      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"Durgesh-byte_GTA-Editor-New" /o:"${{ secrets.SONAR_ORG }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      # Step 5: Build with MSBuild (now Qt is available)
      - name: Build with MSBuild
        run: |
          msbuild GTAAPPLICATION.sln -t:rebuild -p:Qt5_DIR="C:\Qt\5.15.2\msvc2019_64\lib\cmake\Qt5"  # Adjust path to your Qt version

      # Step 6: End SonarScanner
      - name: End SonarScanner
        run: |
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
