name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for SonarCloud to analyze changes

      # Step 2: Install Qt 5.15.2 using install-qt-action
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: 'C:\Qt'
          install-deps: 'true'

      # Step 3: Set up MSBuild (for Visual Studio build tools)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Step 4: Install SonarCloud build wrapper with enhanced debugging
      - name: Install SonarCloud build wrapper
        run: |
          mkdir sonar-build
          curl -o sonar-build/build-wrapper-win-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
          if exist sonar-build\build-wrapper-win-x86.zip (echo Download successful) else (echo Download failed && exit /b 1)
          unzip sonar-build/build-wrapper-win-x86.zip -d sonar-build
          dir sonar-build
          dir sonar-build\build-wrapper-win-x86 2>nul || dir sonar-build\build-wrapper-win-x86-64 2>nul
          dir sonar-build\build-wrapper-win-x86-64\build-wrapper-win-x86-64.exe 2>nul || echo Build wrapper executable not found
        shell: cmd

      # Step 5: Restore NuGet packages (if your project uses NuGet)
      - name: Restore NuGet packages
        run: |
          msbuild GTAAPPLICATION.sln -t:restore
        shell: cmd

      # Step 6: Build the project with SonarCloud build wrapper
      - name: Build with SonarCloud build wrapper
        run: |
          if exist sonar-build\build-wrapper-win-x86-64\build-wrapper-win-x86-64.exe (
            sonar-build\build-wrapper-win-x86-64\build-wrapper-win-x86-64.exe --out-dir sonar-build msbuild GTAAPPLICATION.sln /t:Rebuild /p:Configuration=Debug /p:Platform=x64
          ) else if exist sonar-build\build-wrapper-win-x86\build-wrapper-win-x86-64.exe (
            sonar-build\build-wrapper-win-x86\build-wrapper-win-x86-64.exe --out-dir sonar-build msbuild GTAAPPLICATION.sln /t:Rebuild /p:Configuration=Debug /p:Platform=x64
          ) else (
            echo Build wrapper not found in expected locations && exit /b 1
          )
        shell: cmd

      # Step 7: Run SonarCloud scanner
      - name: Run SonarCloud scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"Durgesh-byte_GTA-Editor-New" /o:"durgesh-byte" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        shell: cmd
